"""
Performance Observer for v4.1.1 Monitoring
Tracks signals, trades, and determines when to activate v4.2 fallback
"""
import time
from datetime import datetime, timedelta
from typing import Dict, Optional
import threading
from config.config import config


class PerformanceObserver:
    """Monitors v4.1.1 performance and triggers v4.2 fallback if needed"""

    def __init__(self):
        self.start_time: float = time.time()
        self.signals_recorded: int = 0
        self.trades_recorded: int = 0
        self.signal_scores: list = []
        self.trade_results: list = []  # List of (pnl_pct, win_bool) tuples
        self.first_signal_time: Optional[float] = None
        self.v42_activated: bool = False
        self._lock = threading.Lock()

        print(f"✅ PerformanceObserver initialized at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    def record_signal(self, symbol: str, score: float, features: Dict) -> None:
        """Record a signal generated by the scanner"""
        with self._lock:
            self.signals_recorded += 1
            self.signal_scores.append(score)

            if self.first_signal_time is None:
                self.first_signal_time = time.time()

            print(f"[Observer] Signal #{self.signals_recorded}: {symbol} score={score:.1f}")

    def record_trade(self, trade_dict: Dict) -> None:
        """
        Record a closed trade
        Expected trade_dict keys: symbol, entry_price, exit_price, pnl_pct, exit_reason
        """
        with self._lock:
            self.trades_recorded += 1

            pnl_pct = trade_dict.get('pnl_pct', 0.0)
            is_win = pnl_pct > 0

            self.trade_results.append((pnl_pct, is_win))

            print(f"[Observer] Trade #{self.trades_recorded}: {trade_dict.get('symbol')} "
                  f"PnL={pnl_pct:.2f}% ({'WIN' if is_win else 'LOSS'})")

    def get_stats(self) -> Dict:
        """Return current performance statistics"""
        with self._lock:
            runtime_hours = (time.time() - self.start_time) / 3600

            avg_score = sum(self.signal_scores) / len(self.signal_scores) if self.signal_scores else 0.0

            if self.trade_results:
                wins = sum(1 for _, is_win in self.trade_results if is_win)
                win_rate = (wins / len(self.trade_results)) * 100
                avg_pnl = sum(pnl for pnl, _ in self.trade_results) / len(self.trade_results)
            else:
                win_rate = 0.0
                avg_pnl = 0.0

            time_since_first_signal = None
            if self.first_signal_time:
                time_since_first_signal = (time.time() - self.first_signal_time) / 3600

            return {
                'signals': self.signals_recorded,
                'trades': self.trades_recorded,
                'win_rate': win_rate,
                'avg_score': avg_score,
                'avg_pnl': avg_pnl,
                'runtime': f"{runtime_hours:.1f}h",
                'runtime_hours': runtime_hours,
                'time_since_first_signal': time_since_first_signal,
                'v42_activated': self.v42_activated,
                'start_time': datetime.fromtimestamp(self.start_time).strftime('%Y-%m-%d %H:%M:%S'),
            }

    def should_activate_v42(self) -> bool:
        """
        Determine if v4.2 fallback should be activated
        Criteria: Running for >FALLBACK_TRIGGER_HOURS hours AND zero signals generated
        Only activates if ENABLE_V42_FALLBACK is True
        """
        with self._lock:
            if self.v42_activated:
                return False  # Already activated

            if not config.ENABLE_V42_FALLBACK:
                return False  # Fallback disabled

            runtime_hours = (time.time() - self.start_time) / 3600

            should_activate = runtime_hours > config.FALLBACK_TRIGGER_HOURS and self.signals_recorded == 0

            if should_activate:
                self.v42_activated = True
                print(f"[Observer] ⚠️  v4.2 FALLBACK CRITERIA MET: "
                      f"{runtime_hours:.1f}h runtime, {self.signals_recorded} signals")

            return should_activate

    def mark_v42_activated(self) -> None:
        """Mark v4.2 as activated (called when fallback is applied)"""
        with self._lock:
            self.v42_activated = True


# Global observer instance
observer: Optional[PerformanceObserver] = None


def get_observer() -> PerformanceObserver:
    """Get or create the global observer instance"""
    global observer
    if observer is None:
        observer = PerformanceObserver()
    return observer
